Repository AY2021S1-CS2113T-W12-3/tp, pull requests merged in 2020-10, with the labels that each got.

#36 String operations
  src/main/java/seedu/duke/classes/Show.java
  src/main/java/seedu/duke/classes/Storage.java
  src/main/java/seedu/duke/commands/EditCommand.java
  src/main/java/seedu/duke/utility/ErrorHandling.java
  src/main/java/seedu/duke/utility/InputParser.java
  src/main/java/seedu/duke/utility/StringOperations.java
  src/main/java/seedu/duke/utility/Ui.java
Labels: bug, enhancement

#51 Show duration
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/classes/Movie.java
  src/main/java/seedu/duke/classes/Show.java
  src/main/java/seedu/duke/classes/Storage.java
  src/main/java/seedu/duke/classes/WatchTime.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/utility/Ui.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
  src/test/java/seedu/duke/commands/UpdateShowEpisodeProgressCommandTest.java
Labels: enhancement

#52 Update Ui and User Guide
  docs/UserGuide.md
  src/main/java/seedu/duke/utility/InputParser.java
  src/main/java/seedu/duke/utility/StringOperations.java
  src/main/java/seedu/duke/utility/Ui.java
Labels: Functions, documentation

#53 Updated user guide and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/help.PNG
  docs/images/quickstart.PNG
Labels: documentation

#54 added exceptions and watchtime command
  src/main/java/seedu/duke/classes/Show.java
  src/main/java/seedu/duke/classes/WatchTime.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/UpdateShowEpisodeProgressCommand.java
  src/main/java/seedu/duke/commands/UpdateShowSeasonCommand.java
  src/main/java/seedu/duke/utility/InputParser.java
  src/main/java/seedu/duke/utility/ShowList.java
  src/main/java/seedu/duke/utility/Ui.java
Labels: enhancement

#59 Add watch command
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/WatchCommand.java
  src/main/java/seedu/duke/utility/InputParser.java
  src/main/java/seedu/duke/utility/SaveState.java
  src/main/java/seedu/duke/utility/StringOperations.java
  src/main/java/seedu/duke/utility/Ui.java
Labels: enhancement, help wanted

#121 added new utility to parse time
  src/main/java/seedu/duke/commands/EditCommand.java
  src/main/java/seedu/duke/commands/UpdateTimeLimitCommand.java
  src/main/java/seedu/duke/utility/TimeParser.java
  src/test/java/seedu/duke/utility/TimeParserTest.java
Labels: Functions, enhancement

#147 Fixed episode bug
  src/main/java/seedu/duke/commands/UpdateShowEpisodeProgressCommand.java
  src/main/java/seedu/duke/utility/ErrorHandling.java
  src/main/java/seedu/duke/utility/Ui.java
Labels: bug
